### ISSUE TITLE
carousel changes

### ISSUE THREAD

**Issue by IsPeterHere** [Honeycomb-Racing/honeycomb-racing.github.io#2]
Kenneth the carousel padding changes mean the top bar now overlaps and loses definition over the upper carousel upon the website opening, did you mean for this?

**Comment by kamicavi** [comment]
Yes - when the carousel was wrapped in header tags, it created empty space under the navbar which you could scroll up into. If we made the carousel <navbar height> less tall, and added an empty div tag <navbar height> tall above it, and changed navbar-intial style, you could have a blank area you couldn't scroll up into acciedntally, whilst preserving full view of teh carousel I think.

**Comment by IsPeterHere** [comment]
sounds cool!

**Comment by kamicavi** [comment]
Thinking about it, I'm going to add that because we may change what image the carousel has in future, so we wouldn't neccessarily have something that looks good all the time with the image under it
